[general]
# 並列処理のワーカー数
max_workers = 5

[file_extensions]
# 画像ファイルの拡張子
image = ["*.jpg", "*.jpeg", "*.png", "*.gif", "*.bmp", "*.webp"]
# テキストファイルの拡張子
text = ["*.txt", "*.md"]
# CSVファイルの拡張子
csv = ["*.csv"]

[openai]
# 使用するモデル（画像・テキスト共通）
model = "o3-pro-2025-06-10"
# 推論の努力レベル
reasoning_effort = "medium"

[prompt]
# Ankiアプリ用の問題・解答・解説生成プロンプト
content = """
過去問暗記でAnkiアプリに入れるデータを作成したいので、問題・解答・解説・正誤訂正を記載して

全体

- 文字の大きさはすべて同じにして、太字や大文字は使わないで
- 解答・解説に医学的に誤りがある場合は正しい知識で置き換えて、正誤訂正に記載して
- 一般には使われない専門用語は、最後に専門用語と読み方の一覧を記載して

問題について

- 問題番号が与えられている場合は、一番最初に記載して
- 誤字脱字等があれば適切に修正して
- 誤字脱字以外は与えられた文章もしくは画像を改変しないで

解答について

- 問題が選択肢式の場合
    - 問題の選択肢の番号(a,b,cや1,2,3など)だけを列挙し、選択肢の内容は解答に含めないで
    - 選択肢の順番は1,2,3...やa,b,c...で固定して
    - 選択肢の内容が真実の場合は、✅️を行の最初につけて
        - 誤っているものを選べという問題なら、誤っていない(=真実)選択肢に✅️をつけて
    - 選択肢の番号ごとに背景知識を簡潔に1行で説明して
- 問題が記述式の場合
    - 模範解答を記載して

解説について

- 問題を解くうえで身につけておくべき背景知識を体系的に記載して
- 例えば、問題でGERDの症状が問われていた場合、GERDの疾患自体の説明をして
- 必要なら「・」を用いた箇条書きや→を使用して

以下に例を示す。ただし、()は説明なので、実際の出力には入れないこと。

問題10(←問題番号が与えられている場合に書く) 正しい選択肢を選べ(←与えられている問題文。今回は選択肢式)

1. XOはOXに使われている
2. XXではOOの症状がある
3. XXではOXOが治療薬として使われている

解答
1: XXが使われている。XOが使われているのはOOのような場合。
2: ✅️ OOは重要な所見の一つ（←真実を述べている選択肢なので✅️がある）
3: OOの説明。OOはOYが特徴である。XXではBが使われている。

解説

- OO疾患はXXの低下によってOXが引き起こされる病気で、AやB、Cという症状もある。
- 鑑別疾患としてXOがあるが、OOとはこのような違いがある

正誤訂正

- 解答では1番が正解で根拠としてOOが記載されていたが、OOはXXという理由で誤り
- 解答ではOXと記述されていたが、OXはOOという理由で誤り

専門用語

- 幽門狭窄症(ゆうもんきょうさくしょう)
"""
