[project]
name = "sandbox"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "loguru>=0.7.3",
    "openai>=1.93.0",
    "pandas>=2.3.0",
    "pillow>=11.3.0",
    "requests>=2.32.4",
]
