# 写真・動画ファイルのメタデータ復元ツール設定ファイル

[file_types]
# 画像ファイルの拡張子（小文字、ドット付き）
image_extensions = [
    ".jpg",
    ".jpeg", 
    ".png",
    ".gif",
    ".bmp",
    ".tiff",
    ".tif",
    ".webp",
    ".svg",
    ".ico",
    ".heic",
    ".heif",
    ".raw",
    ".cr2",
    ".nef",
    ".arw",
    ".dng",
    ".orf",
    ".rw2",
    ".pef",
    ".srw",
]

# 動画ファイルの拡張子（小文字、ドット付き）
video_extensions = [
    ".mp4",
    ".avi",
    ".mov",
    ".wmv",
    ".flv",
    ".webm",
    ".mkv",
    ".m4v",
    ".3gp",
    ".ogv",
    ".ts",
    ".mts",
    ".m2ts",
    ".vob",
]

